apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app-deployment
  namespace: rishi
spec:
  replicas: 2  # Number of desired replicas/pods
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - name: frontend
        image: public.ecr.aws/g4w2y5n4/frontend:latest  # Replace with your actual container image
        ports:
        - containerPort: 3000  # Replace with the port your application listens on
---

# https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: service-load-balancer-service
  namespace: rishi
spec:
  selector:
    app: front-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
 
